server.port=8035

spring.datasource.url=jdbc:mysql://localhost:3306/ushaMart
spring.datasource.username=root
spring.datasource..password=lkjhgfdsa1
spring.datasource..drive-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.strategy=  org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.defer-datasource-initialization=
data.jpa.repositories.enabled =true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true